//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HW_AIR_S19.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AIR_S19Entities1 : DbContext
    {
        public AIR_S19Entities1()
            : base("name=AIR_S19Entities1")
        {
            Database.SetInitializer(new CreateDatabaseIfNotExists<AIR_S19Entities1>());
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AQUESTION> AQUESTIONs { get; set; }
        public virtual DbSet<AQUESTIONTERM> AQUESTIONTERMs { get; set; }
        public virtual DbSet<ATERM> ATERMs { get; set; }
        public virtual DbSet<EQUESTION> EQUESTIONs { get; set; }
        public virtual DbSet<EQUESTIONTERM> EQUESTIONTERMs { get; set; }
        public virtual DbSet<ETERM> ETERMs { get; set; }
    }
}
